### ISSUE TITLE
initial startup error

### ISSUE THREAD

**Issue by DinoNuggies69uwu** [Glazelf/RiseHax#16]
on startup i get this error
![image](https://user-images.githubusercontent.com/96709228/147429894-a070c546-3147-4dd9-800e-163e20250c33.png)
after installing 5.0.0 i still continue to get this error

**Comment by Glazelf** [comment]
Can you try downloading `.NET Desktop Runtime 5.0.13` from [here](https://dotnet.microsoft.com/en-us/download/dotnet/5.0)?
I think you might have forgotten to install a Desktop Runtime to add compatibility for your machine to run Windows desktop applications.

Let me know if that works.

**Comment by DinoNuggies69uwu** [comment]
solved the issue, thanks
